name: Run Automated Tests

on:
    push:
        branches: [main, developer]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup .NET
            uses: actions/setup-dotnet@v4
            with:
              dotnet-version: '8.0.x'

          - name: Restore dependencies
            run: dotnet restore

          - name: Build project
            run: dotnet build --no-restore

          - name: Run all tests
            run: dotnet test --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

          - name: Upload test results
            uses: actions/upload-artifact@v4
            with:
              name: TestResults
              path: ./TestResults